package core.enums;

public enum ChatType
{
	CHATTING_TYPE_NONE,
	CHATTING_TYPE_ALL,
	CHATTING_TYPE_WHISPER,
	CHATTING_TYPE_REPLY,
	CHATTING_TYPE_TEAM,
	CHATTING_TYPE_CLAN,
	CHATTING_TYPE_LOBBY,
	CHATTING_TYPE_MATCH,
	CHATTING_TYPE_CLAN_MEMBER_PAGE;
}